name: Creting a Github Action with Sonar Cloud
on: push

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '21.0'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven cloud
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=maven-project-reachability -Dsonar.organization=maven-project-reachability -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
